### PR TITLE
Update components.rs with new article previews layout

### LINKED ISSUE #16: Mixing up the format of the home page
so articles are in different layouts, like this:

IMG_7667

but the format doesn't change every time you reload it, just every day different articles are in different positions.

- [ ] draw the layout (or is it same as the image)
- [ ] impl

### PR DESCRIPTION
**Pull request by circles-png**

### CODE REVIEW

**Comment by angusmason** [comment]
can it take up the whole width of the screen and be more divided with lines and stuff

also on mobile it should remain without the different positioning stuff, just how it was before this pull request

**Comment by angusmason** [comment]
right now the format is:

mixed up bit of every article
LATEST
normal latest bit
LIFESTYLE
normal lifestyle bit
BUSINESS
normal business bit

and so on but it should be:

LATEST
mixed up latest bit
LIFESTYLE
mixed up lifestyle bit
BUSINESS
mixed up business bit

and so on

**Comment by angusmason** [comment]
and also the LATEST mixed up bit should be a different layout to the other ones, with eight articles

then each category mixed up bit should be five articles, in the layout
BIG ONE ON THE RIGHT | small one here | small one here
BIG ONE ON THE RIGHT | small one here | small one here

(that big one on the right is the same one)

**Comment by circles-png** [comment]
ok

**Comment by angusmason** [comment]
remove word LATEST, but keep that first horizontal line to separate the category menu from the articles
then put title of the top left article ABOVE the image, and make the text bigger and the image smaller
make the articles on the right hand column (right of the vertical line) not have images, just the text
in general make the text bigger and images smaller cos right now it seems like the images are the main thing, but the text should be

**Pull request merged**
